spring.application.name=Estoque_Aline
# Banco H2 pra testes
spring.datasource.url=jdbc:h2:mem:estoque-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=ig
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

file.path=uploads

