spring.application.name=Estoque_Aline

# Configuração do Banco de Dados SQLite Local
spring.datasource.url=jdbc:sqlite:estoque.db
spring.datasource.driverClassName=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Força o Spring a inicializar os dados (caso tenha um arquivo data.sql)
spring.jpa.defer-datasource-initialization=true

# Configurações de upload de arquivos mantidas
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
file.path=src/main/resources/static/images/
