INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 1');
INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 2');
INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 3');
INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 4');
INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 5');
INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 6');
INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 7');
INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 8');
INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 9');
INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 10');
INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 11');
INSERT INTO caixa_db (codigo_caixa) VALUES ('Caixa 12');

INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Sabonete', 'Ekos', '2027-10-18', 'http://localhost:8080/imagens/texto-teste-img.jpg', 22, 7, 154, 1);
INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Homo Essence', 'Perfume', '2029-12-10', 'http://localhost:8080/imagens/texto-teste-img.jpg', 110, 5, 550, 1);
INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Hidratante de Algodão', 'Hidratante', '2026-12-25', 'http://localhost:8080/imagens/texto-teste-img.jpg', 32, 15, 480, 2);
INSERT INTO produto_db (nome, categoria, imagem_url, preco, quantidade, preco_total, caixa_id) VALUES ('Bolsinha', 'Aleatório', 'http://localhost:8080/imagens/texto-teste-img.jpg', 0, 1, 0, 3);
INSERT INTO produto_db (nome, categoria, validade, imagem_url, preco, quantidade, preco_total, caixa_id) VALUES ('Kaiak', 'Perfume', '2029-11-05', 'http://localhost:8080/imagens/texto-teste-img.jpg', 85, 12, 1020, 4);
INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Shampoo', 'Ekos', '2027-12-18', 'http://localhost:8080/imagens/texto-teste-img.jpg', 28, 22, 616, 4);
INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Sabonete', 'Ekos', '2027-10-18', 'http://localhost:8080/imagens/texto-teste-img.jpg', 22, 7, 154, 4);
INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Homo Essence', 'Perfume', '2029-12-10', 'http://localhost:8080/imagens/texto-teste-img.jpg', 110, 5, 550, 5);
INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Hidratante de Algodão', 'Hidratante', '2026-12-25', 'http://localhost:8080/imagens/texto-teste-img.jpg', 32, 15, 480, 7);
INSERT INTO produto_db (nome, categoria, imagem_url, preco, quantidade, preco_total, caixa_id) VALUES ('Bolsinha', 'Aleatório', 'http://localhost:8080/imagens/texto-teste-img.jpg', 0, 1, 0, 10);
INSERT INTO produto_db (nome, categoria, validade, imagem_url, preco, quantidade, preco_total, caixa_id) VALUES ('Kaiak', 'Perfume', '2029-11-05', 'http://localhost:8080/imagens/texto-teste-img.jpg', 85, 12, 1020, 11);
INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Shampoo', 'Ekos', '2027-12-18', 'http://localhost:8080/imagens/texto-teste-img.jpg', 28, 22, 616, 8);
INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Sabonete', 'Ekos', '2027-10-18', 'http://localhost:8080/imagens/texto-teste-img.jpg', 22, 7, 154, 4);
INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Homo Essence', 'Perfume', '2029-12-10', 'http://localhost:8080/imagens/texto-teste-img.jpg', 110, 5, 550, 9);
INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Hidratante de Algodão', 'Hidratante', '2026-12-25', 'http://localhost:8080/imagens/texto-teste-img.jpg', 32, 15, 480, 9);
INSERT INTO produto_db (nome, categoria, imagem_url, preco, quantidade, preco_total, caixa_id) VALUES ('Bolsinha', 'Aleatório', 'http://localhost:8080/imagens/texto-teste-img.jpg', 0, 1, 0, 9);
INSERT INTO produto_db (nome, categoria, validade, imagem_url, preco, quantidade, preco_total, caixa_id) VALUES ('Kaiak', 'Perfume', '2029-11-05', 'http://localhost:8080/imagens/texto-teste-img.jpg', 85, 12, 1020, 10);
INSERT INTO produto_db (nome, categoria, validade, imagem_url,  preco, quantidade, preco_total, caixa_id) VALUES ('Shampoo', 'Ekos', '2027-12-18', 'http://localhost:8080/imagens/texto-teste-img.jpg', 28, 22, 616, 10);